;-----------------------------------------------------------------------------
; {{PROJECT_NAME}} - Dynamic Link Library
;-----------------------------------------------------------------------------
; Template: MASM64 DLL
; Generated by MASM64 Framework
;-----------------------------------------------------------------------------

OPTION CASEMAP:NONE

;-----------------------------------------------------------------------------
; Includes
;-----------------------------------------------------------------------------
INCLUDE \masm64-framework\core\abi64.inc
INCLUDE \masm64-framework\core\stack64.inc
INCLUDE \masm64-framework\core\macros64.inc

;-----------------------------------------------------------------------------
; DLL Entry Reasons
;-----------------------------------------------------------------------------
DLL_PROCESS_ATTACH  EQU 1
DLL_THREAD_ATTACH   EQU 2
DLL_THREAD_DETACH   EQU 3
DLL_PROCESS_DETACH  EQU 0

;-----------------------------------------------------------------------------
; External Win32 API
;-----------------------------------------------------------------------------
EXTERNDEF DisableThreadLibraryCalls:PROC

;-----------------------------------------------------------------------------
; Data Section
;-----------------------------------------------------------------------------
.DATA

g_hModule   QWORD 0

;-----------------------------------------------------------------------------
; Code Section
;-----------------------------------------------------------------------------
.CODE

;-----------------------------------------------------------------------------
; DllMain - DLL Entry Point
;-----------------------------------------------------------------------------
; Parameters:
;   RCX = hinstDLL
;   EDX = fdwReason
;   R8  = lpvReserved
;-----------------------------------------------------------------------------
DllMain PROC FRAME
    push rbp
    .pushreg rbp
    push rbx
    .pushreg rbx
    sub rsp, 40
    .allocstack 40
    lea rbp, [rsp + 32]
    .setframe rbp, 32
    .endprolog
    
    mov rbx, rcx                        ; Save hinstDLL
    
    cmp edx, DLL_PROCESS_ATTACH
    je process_attach
    
    cmp edx, DLL_PROCESS_DETACH
    je process_detach
    
    ; DLL_THREAD_ATTACH/DETACH - do nothing
    jmp success
    
process_attach:
    ; Save module handle
    mov g_hModule, rbx
    
    ; Disable thread notifications for performance
    mov rcx, rbx
    call DisableThreadLibraryCalls
    
    ; Add initialization code here
    
    jmp success
    
process_detach:
    ; Add cleanup code here
    jmp success
    
success:
    mov eax, 1                          ; TRUE
    jmp done
    
fail:
    xor eax, eax                        ; FALSE
    
done:
    add rsp, 40
    pop rbx
    pop rbp
    ret
DllMain ENDP

;-----------------------------------------------------------------------------
; Exported Functions
;-----------------------------------------------------------------------------

;-----------------------------------------------------------------------------
; ExampleFunction - Example exported function
;-----------------------------------------------------------------------------
; Parameters: RCX = param1, RDX = param2
; Returns: Result in RAX
;-----------------------------------------------------------------------------
ExampleFunction PROC FRAME
    sub rsp, SHADOW_SPACE
    .allocstack SHADOW_SPACE
    .endprolog
    
    ; Add your code here
    mov rax, rcx
    add rax, rdx
    
    add rsp, SHADOW_SPACE
    ret
ExampleFunction ENDP

;-----------------------------------------------------------------------------
; GetVersion - Return DLL version
;-----------------------------------------------------------------------------
GetVersion PROC
    mov eax, 00010000h                  ; Version 1.0
    ret
GetVersion ENDP

END

