;-----------------------------------------------------------------------------
; {{PROJECT_NAME}} - GUI Application
;-----------------------------------------------------------------------------
; Template: MASM64 Win32 GUI Application
; Generated by MASM64 Framework
;-----------------------------------------------------------------------------

OPTION CASEMAP:NONE

;-----------------------------------------------------------------------------
; Includes
;-----------------------------------------------------------------------------
INCLUDE \masm64-framework\core\abi64.inc
INCLUDE \masm64-framework\core\stack64.inc
INCLUDE \masm64-framework\core\macros64.inc

;-----------------------------------------------------------------------------
; External Win32 API
;-----------------------------------------------------------------------------
EXTERNDEF GetModuleHandleW:PROC
EXTERNDEF RegisterClassExW:PROC
EXTERNDEF CreateWindowExW:PROC
EXTERNDEF ShowWindow:PROC
EXTERNDEF UpdateWindow:PROC
EXTERNDEF GetMessageW:PROC
EXTERNDEF TranslateMessage:PROC
EXTERNDEF DispatchMessageW:PROC
EXTERNDEF PostQuitMessage:PROC
EXTERNDEF DefWindowProcW:PROC
EXTERNDEF LoadCursorW:PROC
EXTERNDEF ExitProcess:PROC

;-----------------------------------------------------------------------------
; Window Messages
;-----------------------------------------------------------------------------
WM_DESTROY      EQU 2
WM_CLOSE        EQU 10h
WM_PAINT        EQU 0Fh

;-----------------------------------------------------------------------------
; Window Styles
;-----------------------------------------------------------------------------
WS_OVERLAPPEDWINDOW EQU 0CF0000h
WS_VISIBLE      EQU 10000000h

;-----------------------------------------------------------------------------
; ShowWindow Commands
;-----------------------------------------------------------------------------
SW_SHOWDEFAULT  EQU 10

;-----------------------------------------------------------------------------
; Cursor IDs
;-----------------------------------------------------------------------------
IDC_ARROW       EQU 32512

;-----------------------------------------------------------------------------
; Class Style
;-----------------------------------------------------------------------------
CS_HREDRAW      EQU 2
CS_VREDRAW      EQU 1

;-----------------------------------------------------------------------------
; CW_USEDEFAULT
;-----------------------------------------------------------------------------
CW_USEDEFAULT   EQU 80000000h

;-----------------------------------------------------------------------------
; Structures
;-----------------------------------------------------------------------------
WNDCLASSEXW STRUCT
    cbSize          DWORD ?
    style           DWORD ?
    lpfnWndProc     QWORD ?
    cbClsExtra      DWORD ?
    cbWndExtra      DWORD ?
    hInstance       QWORD ?
    hIcon           QWORD ?
    hCursor         QWORD ?
    hbrBackground   QWORD ?
    lpszMenuName    QWORD ?
    lpszClassName   QWORD ?
    hIconSm         QWORD ?
WNDCLASSEXW ENDS

POINT STRUCT
    x   DWORD ?
    y   DWORD ?
POINT ENDS

MSG STRUCT
    hwnd        QWORD ?
    message     DWORD ?
    padding1    DWORD ?
    wParam      QWORD ?
    lParam      QWORD ?
    time        DWORD ?
    pt          POINT <>
    padding2    DWORD ?
MSG ENDS

;-----------------------------------------------------------------------------
; Data Section
;-----------------------------------------------------------------------------
.DATA

WSTR wszClassName, "MASM64WindowClass"
WSTR wszWindowTitle, "{{PROJECT_NAME}}"

hInstance   QWORD 0
hMainWnd    QWORD 0

;-----------------------------------------------------------------------------
; Code Section
;-----------------------------------------------------------------------------
.CODE

;-----------------------------------------------------------------------------
; WndProc - Window Procedure
;-----------------------------------------------------------------------------
WndProc PROC FRAME
    push rbp
    .pushreg rbp
    sub rsp, 32
    .allocstack 32
    lea rbp, [rsp + 32]
    .setframe rbp, 32
    .endprolog
    
    ; RCX = hwnd, EDX = uMsg, R8 = wParam, R9 = lParam
    
    cmp edx, WM_DESTROY
    je handle_destroy
    
    cmp edx, WM_CLOSE
    je handle_close
    
    ; Default processing
    call DefWindowProcW
    jmp done
    
handle_close:
    ; Could add confirmation dialog here
    call DefWindowProcW
    jmp done
    
handle_destroy:
    xor ecx, ecx
    call PostQuitMessage
    xor eax, eax
    
done:
    add rsp, 32
    pop rbp
    ret
WndProc ENDP

;-----------------------------------------------------------------------------
; WinMain - Entry Point
;-----------------------------------------------------------------------------
WinMain PROC FRAME
    LOCAL wc:WNDCLASSEXW
    LOCAL msg:MSG
    
    push rbp
    .pushreg rbp
    push rbx
    .pushreg rbx
    push rdi
    .pushreg rdi
    push rsi
    .pushreg rsi
    sub rsp, 200
    .allocstack 200
    lea rbp, [rsp + 32]
    .setframe rbp, 32
    .endprolog
    
    ; Get module handle
    xor ecx, ecx
    call GetModuleHandleW
    mov hInstance, rax
    mov rsi, rax
    
    ; Load cursor
    xor ecx, ecx
    mov edx, IDC_ARROW
    call LoadCursorW
    mov rdi, rax                        ; Save cursor handle
    
    ; Register window class
    lea rbx, wc
    mov DWORD PTR [rbx].WNDCLASSEXW.cbSize, SIZEOF WNDCLASSEXW
    mov DWORD PTR [rbx].WNDCLASSEXW.style, CS_HREDRAW OR CS_VREDRAW
    lea rax, WndProc
    mov [rbx].WNDCLASSEXW.lpfnWndProc, rax
    mov DWORD PTR [rbx].WNDCLASSEXW.cbClsExtra, 0
    mov DWORD PTR [rbx].WNDCLASSEXW.cbWndExtra, 0
    mov [rbx].WNDCLASSEXW.hInstance, rsi
    mov QWORD PTR [rbx].WNDCLASSEXW.hIcon, 0
    mov [rbx].WNDCLASSEXW.hCursor, rdi
    mov QWORD PTR [rbx].WNDCLASSEXW.hbrBackground, 6     ; COLOR_WINDOW + 1
    mov QWORD PTR [rbx].WNDCLASSEXW.lpszMenuName, 0
    lea rax, wszClassName
    mov [rbx].WNDCLASSEXW.lpszClassName, rax
    mov QWORD PTR [rbx].WNDCLASSEXW.hIconSm, 0
    
    mov rcx, rbx
    call RegisterClassExW
    test ax, ax
    jz exit_fail
    
    ; Create window
    ; CreateWindowExW(dwExStyle, lpClassName, lpWindowName, dwStyle,
    ;                 x, y, nWidth, nHeight, hWndParent, hMenu, hInstance, lpParam)
    xor ecx, ecx                        ; dwExStyle
    lea rdx, wszClassName               ; lpClassName
    lea r8, wszWindowTitle              ; lpWindowName
    mov r9d, WS_OVERLAPPEDWINDOW OR WS_VISIBLE  ; dwStyle
    mov DWORD PTR [rsp + 32], CW_USEDEFAULT     ; x
    mov DWORD PTR [rsp + 40], CW_USEDEFAULT     ; y
    mov DWORD PTR [rsp + 48], 800               ; nWidth
    mov DWORD PTR [rsp + 56], 600               ; nHeight
    mov QWORD PTR [rsp + 64], 0                 ; hWndParent
    mov QWORD PTR [rsp + 72], 0                 ; hMenu
    mov [rsp + 80], rsi                         ; hInstance
    mov QWORD PTR [rsp + 88], 0                 ; lpParam
    call CreateWindowExW
    test rax, rax
    jz exit_fail
    mov hMainWnd, rax
    
    ; Show window
    mov rcx, rax
    mov edx, SW_SHOWDEFAULT
    call ShowWindow
    
    ; Update window
    mov rcx, hMainWnd
    call UpdateWindow
    
    ; Message loop
msg_loop:
    lea rcx, msg
    xor edx, edx                        ; hWnd = NULL (all windows)
    xor r8d, r8d                        ; wMsgFilterMin
    xor r9d, r9d                        ; wMsgFilterMax
    call GetMessageW
    test eax, eax
    jz exit_ok
    cmp eax, -1
    je exit_fail
    
    lea rcx, msg
    call TranslateMessage
    
    lea rcx, msg
    call DispatchMessageW
    
    jmp msg_loop
    
exit_ok:
    lea rax, msg
    mov eax, DWORD PTR [rax].MSG.wParam
    jmp exit
    
exit_fail:
    mov eax, 1
    
exit:
    add rsp, 200
    pop rsi
    pop rdi
    pop rbx
    pop rbp
    
    mov ecx, eax
    call ExitProcess
    
    ret
WinMain ENDP

END

