;-----------------------------------------------------------------------------
; {{PROJECT_NAME}} - Console Application
;-----------------------------------------------------------------------------
; Template: MASM64 Console Application
; Generated by MASM64 Framework
;-----------------------------------------------------------------------------

OPTION CASEMAP:NONE

;-----------------------------------------------------------------------------
; Includes
;-----------------------------------------------------------------------------
INCLUDE \masm64-framework\core\abi64.inc
INCLUDE \masm64-framework\core\stack64.inc
INCLUDE \masm64-framework\core\macros64.inc

;-----------------------------------------------------------------------------
; External Win32 API
;-----------------------------------------------------------------------------
EXTERNDEF GetStdHandle:PROC
EXTERNDEF WriteConsoleW:PROC
EXTERNDEF ExitProcess:PROC

;-----------------------------------------------------------------------------
; Constants
;-----------------------------------------------------------------------------
STD_OUTPUT_HANDLE       EQU -11

;-----------------------------------------------------------------------------
; Data Section
;-----------------------------------------------------------------------------
.DATA

WSTR wszHello, "Hello from MASM64 Framework!"
wszNewLine  DW 13, 10, 0

;-----------------------------------------------------------------------------
; BSS Section
;-----------------------------------------------------------------------------
.DATA?

hStdOut     QWORD ?
dwWritten   DWORD ?

;-----------------------------------------------------------------------------
; Code Section
;-----------------------------------------------------------------------------
.CODE

;-----------------------------------------------------------------------------
; WinMain - Entry Point
;-----------------------------------------------------------------------------
WinMain PROC FRAME
    push rbp
    .pushreg rbp
    sub rsp, 48
    .allocstack 48
    lea rbp, [rsp + 32]
    .setframe rbp, 32
    .endprolog
    
    ; Get stdout handle
    mov ecx, STD_OUTPUT_HANDLE
    call GetStdHandle
    mov hStdOut, rax
    
    ; Write message
    mov rcx, rax                        ; hConsoleOutput
    lea rdx, wszHello                   ; lpBuffer
    mov r8d, 28                         ; nNumberOfCharsToWrite
    lea r9, dwWritten                   ; lpNumberOfCharsWritten
    mov QWORD PTR [rsp + 32], 0         ; lpReserved
    call WriteConsoleW
    
    ; Write newline
    mov rcx, hStdOut
    lea rdx, wszNewLine
    mov r8d, 2
    lea r9, dwWritten
    mov QWORD PTR [rsp + 32], 0
    call WriteConsoleW
    
    ; Exit
    xor ecx, ecx
    call ExitProcess
    
    ; Never reached
    lea rsp, [rbp - 32 + 48]
    pop rbp
    ret
WinMain ENDP

END

